name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/mohit.pem
          chmod 400 ~/.ssh/mohit.pem
          ssh-keyscan -H ${{ secrets.KNOWN_HOST }} > ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -i ~/.ssh/mohit.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.KNOWN_HOST }} << 'EOF'
            cd ~/devops-part
            git pull origin main
            pnpm install
            pnpm run build
            pm2 stop all || true
            pm2 delete all || true

            pm2 start npm --name "http-server" -- start --cwd ~/devops-part/apps/http-server
            pm2 start npm --name "ws-server" -- start   --cwd ~/devops-part/apps/ws-server
            pm2 start npm --name "next-server" -- start --cwd ~/devops-part/apps/web 

            pm2 save
          EOF