name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ec2.pem
          chmod 400 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Load Node (NVM)
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            corepack enable
            corepack prepare pnpm@latest --activate

            # Ensure PM2
            command -v pm2 >/dev/null || npm i -g pm2

            cd ~/devops-part
            git pull origin main

            pnpm install
            pnpm run build

            pm2 stop all || true
            pm2 delete all || true

            pm2 start npm --name http-server -- start --cwd apps/http-server
            pm2 start npm --name ws-server   -- start --cwd apps/ws-server
            pm2 start npm --name next-server -- start --cwd apps/web

            pm2 save
          EOF
